### ISSUE TITLE
"Shader compilation failures are fatal" error when running with the scene view extension enabled

### ISSUE THREAD

**Issue by OrangeLightning219** [A57R4L/SceneViewExtensionTemplate#2]
Hi.

Based on your repository I made my own plugin that contains a custom SceneViewExtension but I'm getting the "Shader compilation failures are fatal" error when starting the engine. 

This gist contains the code and the error log: [https://gist.github.com/OrangeLightning219/06fba3f2ed7315ef792bf19f26e131fe](https://gist.github.com/OrangeLightning219/06fba3f2ed7315ef792bf19f26e131fe)

When inspecting the `Shader` variable in the `MaterialUtils.cpp` file on line 97 it looks like the shader compiled fine - it's not null, the code size variable is set, the number of parameters match what I declared etc.

I'm using UE 5.4.

I've been trying to figure this out for many hours but there's almost no information about custom shaders on the internet. Do you have any ideas what may be causing this error?

**Comment by A57R4L** [comment]
I think the main issue here is that while the shader compiles, the parameters don't match with your setup. I'm not 100% sure, but I think you are not able to get the Texcoord input on a setup like this. So try something like this for example to the shader file:

```
void MainPS( 
			float4 Position : SV_Position,
			 out float4 OutColor : SV_Target0 )

{
	const float2 UV = Position.xy * Output_ExtentInverse;
	OutColor = float4( 1.0f, 0.0f, 0.0f, 1.0f )  * InputTexture.Sample( InputSampler, UV );
}
```

And then on your shader binding side you set up the shader parameters accordingly. Also with a rendertarget binding, you need to setup the output texture flags to be RenderTargetable if that fails with your SceneColor settings, but that should give you a proper error in the log though.

**Comment by OrangeLightning219** [comment]
It's working now. I had to do it like this:

```
#include "/Engine/Private/ScreenPass.ush"

SCREEN_PASS_TEXTURE_VIEWPORT( ViewParams );

float2 GetUV( float4 Position )
{
    float2 ViewportUV = ( ( Position.xy - ViewParams_ViewportMin.xy ) * ViewParams_ViewportSizeInverse.xy );
    return ViewportUV * ViewParams_UVViewportSize + ViewParams_UVViewportMin;
}
```

Thanks for pointing me in the right direction. 👍
